### ISSUE TITLE
Issues in BIG and DBIG Prototypes

### ISSUE THREAD

**Issue by jstuczyn** [milagro-crypto/milagro-crypto-js#28]
Hi there!

I've been using your library for some time and I've found issues in the BIG and DBIG prototypes. It involves using negative numbers for the modulo operation.

Take this sample code:
```javascript
let ctx = new CTX('BN254');
let b1 = new ctx.BIG(-5);
let b2 = new ctx.BIG(13);
b1.mod(b2);
console.log(b1.toString()) // this will cause an infinite loop
```

You could do the following to prevent the loop (in this particular example):
```javascript
let ctx = new CTX('BN254');
let b1 = new ctx.BIG(-5);
let b2 = new ctx.BIG(13);
b1.mod(b2);
b1.add(b2);
b1.norm();
console.log(b1.toString()) // this will now work correctly
```

However, the case of DBIG is slightly more tricky. Take: 
```javascript
let ctx = new CTX('BN254');
let db1 = new ctx.DBIG(-5);
let db2 = new ctx.DBIG(13);
let db3 = db1.mod(db2)

let b1 = new ctx.BIG(-5);
let b2 = new ctx.BIG(13);
b1.mod(b2);

console.log(db3, b1); // in principle both results should be identical, yet there is an incorrect carry for db3
```

If you need any more information, I'll be more than happy to help!

**Comment by mcarrickscott** [comment]
Hello Jedrzej,

The simple reason for this behavior is that, as it says in the AMCL
documentation, "AMCL has no support for negative numbers".

In fact in this kind of cryptography negative numbers are rarely needed.
Almost all arithmetic takes place inside of a field, with respect to a
modulus q. In this case the negative number -x is mathematically equivalent
to the positive number q-x, so we simply use q-x instead of -x.

Note that not supporting negative numbers does not mean that subtraction is
impossible. It works just fine as long as the smaller number is always
subtracted from the bigger number. We make sure that this is always the
case. If a negative number should ever arise as a result of subtraction,
the program would probably crash!

However in rare cases negative numbers must be handled. In these cases the
sign of the number must be handled separately, the maths done with the
positive equivalent, and the correct sign restored to the final result.

We could have developed a representation that processed negative numbers
correctly, but since it would be so rarely used we thought it better to
support only positive numbers efficiently, and deal with the very
occasional requirement for negative numbers on a case-by-case basis.

Mike
